# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     increment_build_number(xcodeproj: "CodeLounge.xcodeproj")
#     build_app(scheme: "CodeLounge")
#     upload_to_testflight
#   end
# end

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight using Fastlane Match"
  lane :beta do

    # 📈 빌드 넘버 증가
    increment_build_number(xcodeproj: "CodeLounge.xcodeproj")

    # 🏗️ 앱 빌드 및 서명
    build_app(
      scheme: "CodeLounge",
      export_options: {
        provisioningProfiles: {
          "com.indextrown.CodeLounge" => "com.indextrown.CodeLounge"
        }
      }
    )

    # App Store Connect API 키 생성 (환경변수로부터 값 불러오기)
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      in_house: false
    )

    # 🚀 TestFlight 업로드
    upload_to_testflight(api_key: api_key)
  end  
end

