# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# name: Build and Deploy

# on:
#   push:
#     branches: [ "release" ]

# jobs:
#   build:
#     runs-on: macos-latest
#     env:
#       APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
#       APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
#       APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3.1.2

#       - name: Install dependencies
#         run: bundle install

#       - name: Run fastlane beta
#         run: bundle exec fastlane beta

name: Build and Deploy iOS App

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    steps:
      # 프로젝트 레포 클론 (일반 인증 방식 사용)
      - name: Checkout Project Repo
        uses: actions/checkout@v2

      # SSH 키 설치 (Deploy Key는 private 레포 접근에 사용)
      - name: Install SSH Key for Private Repo
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}         # Deploy Key로 사용
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Install Dependencies
        run: bundle install

      - name: Run fastlane beta
        run: bundle exec fastlane beta
